{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Test exposing (..)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 2.3.0
- `protoc` 3.21.9
- the following specification file: `test.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.1.0) version latest or higher.


-}

import Protobuf.Decode
import Protobuf.Encode


{-| Default for PongResponse. Should only be used for 'required' decoders as an initial value.


-}
defaultPongResponse : PongResponse
defaultPongResponse =
    { message = "" }


{-| Decode a `PongResponse` from Bytes


-}
decodePongResponse : Protobuf.Decode.Decoder PongResponse
decodePongResponse =
    Protobuf.Decode.message
        defaultPongResponse
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | message = a }) ]


{-| Encode a `PongResponse` to Bytes


-}
encodePongResponse : PongResponse -> Protobuf.Encode.Encoder
encodePongResponse value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.string value.message ) ]


{-| `PongResponse` message


-}
type alias PongResponse =
    { message : String }


{-| Default for PingRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultPingRequest : PingRequest
defaultPingRequest =
    { name = "" }


{-| Decode a `PingRequest` from Bytes


-}
decodePingRequest : Protobuf.Decode.Decoder PingRequest
decodePingRequest =
    Protobuf.Decode.message
        defaultPingRequest
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | name = a }) ]


{-| Encode a `PingRequest` to Bytes


-}
encodePingRequest : PingRequest -> Protobuf.Encode.Encoder
encodePingRequest value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.string value.name ) ]


{-| `PingRequest` message


-}
type alias PingRequest =
    { name : String }
